Repository Camyo-ISPP/CamyoApp, pull requests merged in 2025-05, with the labels that each got.

#286 Eliminar rutas de suscripción y oferta que permitían saltarse el pago
  backend/src/loadtest/locustfile_oferta.py
  backend/src/main/java/com/camyo/backend/oferta/OfertaController.java
  backend/src/main/java/com/camyo/backend/suscripcion/SuscripcionController.java
  backend/src/test/java/com/camyo/backend/Oferta/OfertaControllerTests.java
  backend/src/test/java/com/camyo/backend/Suscripcion/SuscripcionControllerTests.java
  frontend/app/(protected)/suscripcion/index.tsx
Labels: Review effort 2/5

#289 Frontend: Test de pago y pantalla de suscripciones
  backend/src/test/java/com/camyo/backend/UI/CompraTest.java
Labels: Review effort 2/5

#279 Frontend: arreglos interfaz y uso camionero
  frontend/app/oferta/[ofertaid].tsx
Labels: feat, Review effort 3/5

#291 Add autotesting workflow
  .github/workflows/tests.yml
Labels: Review effort 2/5

#290 Añadir test UI de chat
  backend/src/test/java/com/camyo/backend/UI/ChatUITest.java
  frontend/app/oferta/[ofertaid].tsx
Labels: Review effort 2/5, frontend
