Repository Camyo-ISPP/CamyoApp, pull requests merged in 2025-03, with the labels that each got.

#32 Barra de Navegación Web
  frontend/app/ExampleScreen.tsx
  frontend/app/HomeScreen.tsx
  frontend/app/_layout.tsx
  frontend/app/components/BottomBar.jsx
  frontend/app/components/CamyoNabBar.jsx
  frontend/app/index.tsx
  frontend/assets/images/CamyoApp.png
  frontend/assets/images/camyo.png
  frontend/package-lock.json
  frontend/package.json
  package-lock.json
Labels: Review effort 3/5

#29 Modelo repositorio y Servicio de ofertas
  backend/src/main/java/com/camyo/backend/oferta/Carga.java
  backend/src/main/java/com/camyo/backend/oferta/Jornada.java
  backend/src/main/java/com/camyo/backend/oferta/Licencia.java
  backend/src/main/java/com/camyo/backend/oferta/Oferta.java
  backend/src/main/java/com/camyo/backend/oferta/OfertaEstado.java
  backend/src/main/java/com/camyo/backend/oferta/OfertaRepository.java
  backend/src/main/java/com/camyo/backend/oferta/OfertaService.java
  backend/src/main/java/com/camyo/backend/oferta/Trabajo.java
  backend/target/classes/com/camyo/backend/oferta/Carga.class
  backend/target/classes/com/camyo/backend/oferta/Jornada.class
  backend/target/classes/com/camyo/backend/oferta/Licencia.class
  backend/target/classes/com/camyo/backend/oferta/Oferta.class
  backend/target/classes/com/camyo/backend/oferta/OfertaEstado.class
  backend/target/classes/com/camyo/backend/oferta/OfertaRepository.class
  backend/target/classes/com/camyo/backend/oferta/OfertaService.class
  backend/target/classes/com/camyo/backend/oferta/OfertaTipo.class
  backend/target/classes/com/camyo/backend/oferta/Semirremolque.class
  backend/target/classes/com/camyo/backend/oferta/Trabajo.class
Labels: Review effort 3/5

#24 Añadir workflow de comprobación de conventional commits
  .github/workflows/commits.yml
Labels: Review effort 1/5

#33 Seguridad, autenticación y controladores de usuario.
  .gitignore
  INSTALLATION.md
  backend/.env.example
  backend/pom.xml
  backend/src/main/java/com/camyo/backend/BackendApplication.java
  backend/src/main/java/com/camyo/backend/auth/AuthController.java
  backend/src/main/java/com/camyo/backend/auth/AuthService.java
  backend/src/main/java/com/camyo/backend/auth/payload/request/LoginRequest.java
  backend/src/main/java/com/camyo/backend/auth/payload/request/SignupRequest.java
  backend/src/main/java/com/camyo/backend/auth/payload/response/JwtResponse.java
  backend/src/main/java/com/camyo/backend/auth/payload/response/MessageResponse.java
  backend/src/main/java/com/camyo/backend/configuration/DataInitializer.java
  backend/src/main/java/com/camyo/backend/configuration/ExceptionHandlerConfiguration.java
  backend/src/main/java/com/camyo/backend/configuration/SecurityConfiguration.java
  backend/src/main/java/com/camyo/backend/configuration/jwt/AuthEntryPointJwt.java
  backend/src/main/java/com/camyo/backend/configuration/jwt/AuthTokenFilter.java
  backend/src/main/java/com/camyo/backend/configuration/jwt/JwtUtils.java
  backend/src/main/java/com/camyo/backend/configuration/services/UserDetailsImpl.java
  backend/src/main/java/com/camyo/backend/configuration/services/UserDetailsServiceImpl.java
  backend/src/main/java/com/camyo/backend/usuario/Authorities.java
  backend/src/main/java/com/camyo/backend/usuario/AuthoritiesRepository.java
  backend/src/main/java/com/camyo/backend/usuario/AuthoritiesService.java
  backend/src/main/java/com/camyo/backend/usuario/Usuario.java
  backend/src/main/java/com/camyo/backend/usuario/UsuarioController.java
  backend/src/main/java/com/camyo/backend/usuario/UsuarioRepository.java
  backend/src/main/java/com/camyo/backend/usuario/UsuarioService.java
  backend/src/main/resources/application.example.properties
Labels: Review effort 4/5

#30 feat: add base profile page in frontend
  frontend/app/_layout.tsx
  frontend/app/components/BottomBar.jsx
  frontend/app/components/CamyoNabBar.jsx
  frontend/app/user/UserProfileScreen.tsx
  frontend/app/user/css/UserProfileScreen.js
  frontend/package-lock.json
Labels: feat, Review effort 3/5

#38 Fix double encoding error and store email in sign up.
  backend/src/main/java/com/camyo/backend/auth/AuthService.java
Labels: Review effort 2/5

#37 Servicios de ofertas de carga y generales
  backend/src/main/java/com/camyo/backend/oferta/CargaRepository.java
  backend/src/main/java/com/camyo/backend/oferta/CargaService.java
  backend/src/main/java/com/camyo/backend/oferta/OfertaService.java
  backend/src/main/java/com/camyo/backend/oferta/TrabajoRepository.java
  backend/src/main/java/com/camyo/backend/oferta/TrabajoService.java
  backend/target/classes/com/camyo/backend/oferta/Carga.class
  backend/target/classes/com/camyo/backend/oferta/Jornada.class
  backend/target/classes/com/camyo/backend/oferta/Licencia.class
  backend/target/classes/com/camyo/backend/oferta/Oferta.class
  backend/target/classes/com/camyo/backend/oferta/OfertaEstado.class
  backend/target/classes/com/camyo/backend/oferta/OfertaRepository.class
  backend/target/classes/com/camyo/backend/oferta/OfertaService.class
  backend/target/classes/com/camyo/backend/oferta/OfertaTipo.class
  backend/target/classes/com/camyo/backend/oferta/Semirremolque.class
  backend/target/classes/com/camyo/backend/oferta/Trabajo.class
Labels: Review effort 2/5

#35 Añadir workflow de testing automatico
  .github/workflow/run-tests.yml
Labels: Review effort 1/5

#40 Organizar la carpeta de workflows
  .github/workflow/run-tests.yml
Labels: Review effort 1/5

#39 Creación de servicio y controlador de empresa CRUD
  backend/src/main/java/com/camyo/backend/empresa/EmpresaController.java
Labels: Review effort 3/5

#42 Pantalla de registro de usuario inicial
  frontend/app/BooleanSelector.tsx
  frontend/app/Selector.tsx
  frontend/app/_components/BottomBar.jsx
  frontend/app/_components/CamyoNavBar.jsx
  frontend/app/_layout.tsx
  frontend/app/index.tsx
  frontend/app/registro/index.tsx
  frontend/assets/styles/colors.ts
  frontend/assets/styles/globalStyles.ts
  frontend/assets/styles/typography.ts
  frontend/package-lock.json
  frontend/package.json
Labels: Review effort 3/5

#43 Pantalla Perfil de Empresa
  frontend/app/CompanyDetails.tsx
  frontend/app/_components/BooleanSelector.tsx
  frontend/app/_components/CamyoNavBar.jsx
  frontend/app/_components/Selector.tsx
  frontend/app/_components/routes.ts
  frontend/app/_layout.tsx
  frontend/app/miperfilempresa/index.tsx
  frontend/app/registro/index.tsx
Labels: Review effort 2/5

#44 Pantalla login
  frontend/app/_layout.tsx
  frontend/app/login/index.tsx
  frontend/assets/styles/globalStyles.ts
Labels: Review effort 2/5

#47 Pantalla de creación de ofertas
  frontend/app/_components/CamyoNavBar.jsx
  frontend/app/_components/routes.ts
  frontend/app/_layout.tsx
  frontend/app/oferta/crear.tsx
Labels: Review effort 2/5

#48 Login and sign up improvements.
  backend/src/main/java/com/camyo/backend/auth/AuthController.java
  backend/src/main/java/com/camyo/backend/auth/AuthService.java
  backend/src/main/java/com/camyo/backend/auth/payload/request/SignupRequestCamionero.java
  backend/src/main/java/com/camyo/backend/auth/payload/request/SignupRequestEmpresa.java
  backend/src/main/java/com/camyo/backend/camionero/Autonomo.java
  backend/src/main/java/com/camyo/backend/camionero/AutonomoRepository.java
  backend/src/main/java/com/camyo/backend/camionero/AutonomoService.java
  backend/src/main/java/com/camyo/backend/camionero/CamioneroRepository.java
  backend/src/main/java/com/camyo/backend/camionero/CamioneroService.java
  backend/src/main/java/com/camyo/backend/empresa/EmpresaRepository.java
  backend/src/main/java/com/camyo/backend/empresa/EmpresaService.java
Labels: Review effort 3/5

#50 Pantalla Detalle de Oferta
  backend/src/main/java/com/camyo/backend/empresa/EmpresaController.java
  backend/src/main/java/com/camyo/backend/oferta/OfertaController.java
  backend/src/main/java/com/camyo/backend/usuario/UsuarioController.java
  frontend/app/oferta/[ofertaid].tsx
  frontend/assets/images/no-company-logo.png
Labels: Review effort 3/5

#51 Pantalla registro de usuario
  frontend/app/_components/BooleanSelector.tsx
  frontend/app/_components/Selector.tsx
  frontend/app/registro/index.tsx
  frontend/assets/styles/globalStyles.ts
Labels: Review effort 3/5

#46 Controlador servicio de camionero
  backend/src/main/java/com/camyo/backend/camionero/CamioneroController.java
  backend/src/main/java/com/camyo/backend/camionero/CamioneroRepository.java
  backend/src/main/java/com/camyo/backend/camionero/CamioneroService.java
  backend/src/main/java/com/camyo/backend/empresa/EmpresaController.java
Labels: Review effort 3/5

#56 Swagger docs.
  backend/src/main/java/com/camyo/backend/auth/AuthController.java
  backend/src/main/java/com/camyo/backend/usuario/UsuarioController.java
Labels: Review effort 2/5

#54 Migraciones iniciales
  backend/src/main/java/com/camyo/backend/configuration/DataInitializer.java
  backend/src/main/java/com/camyo/backend/oferta/Licencia.java
  backend/src/main/java/com/camyo/backend/oferta/Oferta.java
Labels: Review effort 2/5

#59 Cambiar código de error 400 a 401 en controlador inicio sesión.
  backend/src/main/java/com/camyo/backend/auth/AuthController.java
Labels: Review effort 1/5

#57 Añadir auth context + integrar login con backend
  backend/src/main/java/com/camyo/backend/configuration/DataInitializer.java
  frontend/app/_layout.tsx
  frontend/app/login/index.tsx
  frontend/contexts/AuthContext.tsx
Labels: Review effort 2/5

#60 Controlador del Oferta
  backend/src/main/java/com/camyo/backend/configuration/DataInitializer.java
  backend/src/main/java/com/camyo/backend/oferta/Oferta.java
  backend/src/main/java/com/camyo/backend/oferta/OfertaCompletaDTO.java
  backend/src/main/java/com/camyo/backend/oferta/OfertaController.java
  backend/src/main/java/com/camyo/backend/oferta/OfertaPrioridad.java
  backend/src/main/java/com/camyo/backend/oferta/OfertaRequestDTO.java
  backend/src/main/java/com/camyo/backend/oferta/OfertaService.java
Labels: Review effort 3/5

#74 fix: inicio sesión persiste
  frontend/contexts/AuthContext.tsx
Labels: Review effort 2/5

#75 Add login when button Enter is pressed
  frontend/app/login/index.tsx
Labels: Review effort 1/5

#71 Pantalla Detalles de Oferta
  frontend/app/_layout.tsx
  frontend/app/oferta/[ofertaid].tsx
Labels: Review effort 2/5

#78 Controlador de Oferta
  backend/src/main/java/com/camyo/backend/oferta/OfertaController.java
  backend/src/main/java/com/camyo/backend/oferta/OfertaRepository.java
  backend/src/main/java/com/camyo/backend/oferta/OfertaService.java
Labels: Review effort 2/5

#82 Listado Ofertas
  frontend/app/HomeScreen.tsx
  frontend/app/_components/CamyoNavBar.jsx
  frontend/app/_layout.tsx
  frontend/app/index.tsx
  frontend/assets/images/defaultCompImg.png
Labels: Review effort 3/5

#79 Migraciones piloto
  backend/src/main/java/com/camyo/backend/camionero/Licencia.java
  backend/src/main/java/com/camyo/backend/configuration/DataInitializer.java
  backend/src/main/java/com/camyo/backend/oferta/Licencia.java
  backend/src/main/java/com/camyo/backend/oferta/Oferta.java
  backend/src/main/java/com/camyo/backend/oferta/OfertaCompletaDTO.java
  backend/src/main/java/com/camyo/backend/oferta/OfertaConCargaDTO.java
  backend/src/main/java/com/camyo/backend/oferta/OfertaConTrabajoDTO.java
Labels: Review effort 2/5

#83 Problema de estado de oferta solucionado
  backend/src/main/java/com/camyo/backend/oferta/Oferta.java
Labels: Review effort 1/5

#67 Perfil de usuario con sesión integrada
  backend/src/main/java/com/camyo/backend/configuration/DataInitializer.java
  frontend/app/miperfil/css/UserProfileScreen.js
  frontend/app/miperfil/index.tsx
  frontend/app/oferta/[ofertaid].tsx
  frontend/assets/images/banner_default.jpg
  frontend/assets/images/defaultAvatar.png
  frontend/package-lock.json
Labels: feat, Review effort 4/5

#84 Dividir pantalla de registro en 2
  frontend/app/_components/BooleanSelector.tsx
  frontend/app/_components/MultiSelector.tsx
  frontend/app/_components/Selector.tsx
  frontend/app/registro/camionero.tsx
  frontend/app/registro/empresa.tsx
  frontend/app/registro/index.tsx
  frontend/assets/styles/globalStyles.ts
Labels: Review effort 3/5

#76 SonarQube workflow fix
  .github/workflows/build.yml
  backend/.env.example
  backend/.gitignore
  backend/sonar-project.properties
  backend/src/main/java/com/camyo/backend/configuration/DataInitializer.java
  backend/src/test/java/com/camyo/backend/BackendApplicationTests.java
Labels: Review effort 1/5

#68 Lista de Empresas
  frontend/app/_layout.tsx
  frontend/app/empresas/index.tsx
  frontend/package-lock.json
Labels: Review effort 2/5

#91 Pantallas de edición de usuarios
  backend/src/main/java/com/camyo/backend/usuario/UsuarioService.java
  frontend/app/_components/routes.ts
  frontend/app/miperfil/editar.tsx
  frontend/app/miperfilempresa/editar.tsx
Labels: Review effort 2/5

#69 Pantalla creación ofertas
  frontend/app/oferta/crear.tsx
Labels: Review effort 4/5

#64 Perfil Empresa Mejorado
  frontend/app/miperfilempresa/index.tsx
  frontend/assets/images/empresa.jpg
  frontend/assets/images/image_perfil_empresa.jpg
Labels: Review effort 2/5

#97 Configuración despliegue.
  .gitignore
  backend/.gcloudignore
  backend/app.yaml
  backend/mvnw
  backend/mvnw.cmd
  backend/src/main/java/com/camyo/backend/auth/AuthController.java
  backend/src/main/java/com/camyo/backend/camionero/CamioneroController.java
  backend/src/main/java/com/camyo/backend/configuration/WebConfig.java
  backend/src/main/java/com/camyo/backend/empresa/EmpresaController.java
  backend/src/main/java/com/camyo/backend/oferta/Carga.java
  backend/src/main/java/com/camyo/backend/oferta/Oferta.java
  backend/src/main/java/com/camyo/backend/oferta/OfertaController.java
  backend/src/main/java/com/camyo/backend/usuario/Resena.java
  backend/src/main/java/com/camyo/backend/usuario/Usuario.java
  backend/src/main/java/com/camyo/backend/usuario/UsuarioController.java
  backend/src/main/java/com/camyo/backend/usuario/UsuarioRepository.java
  backend/src/main/java/com/camyo/backend/usuario/UsuarioService.java
  frontend/.firebaserc
  frontend/firebase.json
Labels: Review effort 2/5, Possible security concern

#100 Medio fix
  frontend/app/CompanyDetails.tsx
  frontend/app/_components/BottomBar.jsx
  frontend/app/_components/CamyoNavBar.jsx
  frontend/app/_components/ProfileDropdown.js
  frontend/app/_components/routes.ts
  frontend/app/_layout.tsx
  frontend/app/ejemplo/index.tsx
  frontend/app/index.tsx
  frontend/app/login/index.tsx
  frontend/app/miperfil/index.tsx
  frontend/app/miperfilcamionero/css/UserProfileScreen.js
  frontend/app/miperfilcamionero/editar.tsx
  frontend/app/miperfilcamionero/index.tsx
  frontend/app/miperfilempresa/editar.tsx
  frontend/app/miperfilempresa/index.tsx
  frontend/app/oferta/[ofertaid].tsx
  frontend/app/oferta/crear.tsx
  frontend/app/oferta/editar/[ofertaid].tsx
  frontend/app/perfil/index.tsx
  frontend/app/workinprogress/index.tsx
  frontend/assets/frontendData.json
  frontend/contexts/AuthContext.tsx
Labels: Review effort 3/5

#102 Arreglos
  backend/src/main/java/com/camyo/backend/usuario/UsuarioService.java
  frontend/app/miperfilcamionero/editar.tsx
  frontend/app/miperfilcamionero/index.tsx
  frontend/app/miperfilempresa/editar.tsx
  frontend/contexts/AuthContext.tsx
Labels: Review effort 2/5

#96 Mejoras y detalles
  frontend/app/_components/CamyoNavBar.jsx
  frontend/app/_components/ProfileDropdown.js
  frontend/app/_components/Titulo.tsx
  frontend/app/ejemplo/index.tsx
  frontend/app/empresas/index.tsx
  frontend/app/index.tsx
  frontend/app/login/index.tsx
  frontend/app/oferta/[ofertaid].tsx
  frontend/app/registro/camionero.tsx
  frontend/app/registro/empresa.tsx
  frontend/app/registro/index.tsx
  frontend/assets/images/companyDefaultAvatar.png
  frontend/assets/styles/globalStyles.ts
Labels: Review effort 2/5

#103 fix: applied offer remains applied
  backend/src/main/java/com/camyo/backend/configuration/SecurityConfiguration.java
  frontend/app/login/index.tsx
  frontend/app/miperfilempresa/index.tsx
  frontend/app/oferta/[ofertaid].tsx
  frontend/app/oferta/crear.tsx
  frontend/app/oferta/editar/[ofertaid].tsx
  frontend/app/registro/camionero.tsx
  frontend/app/registro/empresa.tsx
Labels: Review effort 2/5

#119 Create pr-checklist.yml
  .github/workflows/pr-checklist.yml
Labels: Review effort 2/5, frontend

#144 Refactor entities Autnomo and Camionero
  backend/src/main/java/com/camyo/backend/auth/AuthService.java
  backend/src/main/java/com/camyo/backend/auth/payload/request/SignupRequestCamionero.java
  backend/src/main/java/com/camyo/backend/camionero/Autonomo.java
  backend/src/main/java/com/camyo/backend/camionero/AutonomoRepository.java
  backend/src/main/java/com/camyo/backend/camionero/AutonomoService.java
  backend/src/main/java/com/camyo/backend/camionero/Camionero.java
  backend/src/main/java/com/camyo/backend/configuration/DataInitializer.java
  frontend/app/registro/camionero.tsx
Labels: Review effort 2/5

#143 Backend/tarea 33/sistema de suscripciones
  backend/src/main/java/com/camyo/backend/configuration/DataInitializer.java
  backend/src/main/java/com/camyo/backend/suscripcion/PlanNivel.java
  backend/src/main/java/com/camyo/backend/suscripcion/Suscripcion.java
  backend/src/main/java/com/camyo/backend/suscripcion/SuscripcionController.java
  backend/src/main/java/com/camyo/backend/suscripcion/SuscripcionRepository.java
  backend/src/main/java/com/camyo/backend/suscripcion/SuscripcionService.java
Labels: Review effort 2/5

#151 Acceso a perfil de empresa por detalles de oferta
  frontend/app/oferta/[ofertaid].tsx
Labels: Review effort 1/5

#152 Lógica suscripciones provisional.
  backend/src/main/java/com/camyo/backend/auth/AuthService.java
  backend/src/main/java/com/camyo/backend/suscripcion/SuscripcionController.java
  frontend/app/_components/PerfilEmpresa.tsx
  frontend/app/_layout.tsx
  frontend/app/oferta/crear.tsx
  frontend/app/oferta/editar/[ofertaid].tsx
  frontend/contexts/SubscriptionContext.tsx
  frontend/utils/subscriptionRules.ts
  frontend/utils/useSubscriptionRules.ts
Labels: Review effort 3/5, frontend

#153 feat: add new API call that return all data from Ofertas
  backend/src/main/java/com/camyo/backend/oferta/OfertaConTodaInformacionDTO.java
  backend/src/main/java/com/camyo/backend/oferta/OfertaController.java
Labels: Review effort 2/5

#155 Configuración para el deployment del sprint 2.
  backend/src/main/java/com/camyo/backend/configuration/WebConfig.java
  frontend/.firebaserc
  frontend/app.config.js
  frontend/app/(public)/empresas.tsx
  frontend/app/(public)/index.tsx
  frontend/app/(public)/login.tsx
  frontend/app/(public)/registro/camionero.tsx
  frontend/app/(public)/registro/empresa.tsx
  frontend/app/_components/EditarPerfilCamionero.tsx
  frontend/app/_components/EditarPerfilEmpresa.tsx
  frontend/app/_components/PerfilCamionero.tsx
  frontend/app/_components/PerfilEmpresa.tsx
  frontend/app/camionero/[camioneroid].tsx
  frontend/app/empresa/[empresaid].tsx
  frontend/app/oferta/[ofertaid].tsx
  frontend/app/oferta/crear.tsx
  frontend/app/oferta/editar/[ofertaid].tsx
  frontend/contexts/AuthContext.tsx
  frontend/contexts/SubscriptionContext.tsx
  frontend/firebase.json
  frontend/package-lock.json
Labels: build, Review effort 2/5

#154 Perfiles de camionero y empresa, públicos y privados, UX
  frontend/app/(public)/camionero/[camioneroid].tsx
  frontend/app/(public)/empresa/[empresaid].tsx
  frontend/app/(public)/empresas.tsx
  frontend/app/(public)/forbidden.tsx
  frontend/app/(public)/index.tsx
  frontend/app/(public)/login.tsx
  frontend/app/(public)/registro/camionero.tsx
  frontend/app/(public)/registro/empresa.tsx
  frontend/app/(public)/registro/index.tsx
  frontend/app/_components/BackButton.tsx
  frontend/app/_components/BackButtonAbsolute.tsx
  frontend/app/_components/CamyoNavBar.jsx
  frontend/app/_components/PerfilCamionero.tsx
  frontend/app/_components/PerfilEmpresa.tsx
  frontend/app/_components/ProfileDropdown.js
  frontend/app/_components/Titulo.tsx
  frontend/app/_layout.tsx
  frontend/app/_screens/EditarPerfilCamionero.tsx
  frontend/app/_screens/EditarPerfilEmpresa.tsx
  frontend/app/_screens/MiPerfilCamionero.tsx
  frontend/app/_screens/MiPerfilEmpresa.tsx
  frontend/app/_screens/PublicCamionero.tsx
  frontend/app/_screens/PublicEmpresa.tsx
  frontend/app/camionero/[camioneroid].tsx
  frontend/app/camionero/css/CamioneroScreen.js
  frontend/app/empresa/[empresaid].tsx
  frontend/app/miperfil/editar.tsx
  frontend/app/miperfil/index.tsx
  frontend/app/oferta/[ofertaid].tsx
  frontend/app/oferta/crear.tsx
  frontend/app/oferta/editar/[ofertaid].tsx
  frontend/assets/images/camionero.png
  frontend/assets/styles/globalStyles.ts
  frontend/contexts/AuthContext.tsx
  frontend/utils.js
Labels: Review effort 4/5, frontend

#162 Modificaciones y actualización de reseña
  backend/src/main/java/com/camyo/backend/configuration/DataInitializer.java
  backend/src/main/java/com/camyo/backend/configuration/SecurityConfiguration.java
  backend/src/main/java/com/camyo/backend/resena/Resena.java
  backend/src/main/java/com/camyo/backend/resena/ResenaController.java
  backend/src/main/java/com/camyo/backend/resena/ResenaRepository.java
  backend/src/main/java/com/camyo/backend/resena/ResenaService.java
  backend/src/main/java/com/camyo/backend/usuario/Usuario.java
  backend/src/main/java/com/camyo/backend/usuario/UsuarioController.java
  backend/src/main/java/com/camyo/backend/usuario/UsuarioRepository.java
  backend/src/main/java/com/camyo/backend/usuario/UsuarioService.java
Labels: Review effort 3/5

#157 Pantalla suscripciones
  frontend/app/_components/CamyoNavBar.jsx
  frontend/app/_components/routes.ts
  frontend/app/_layout.tsx
  frontend/app/_screens/MiPerfilEmpresa.tsx
  frontend/app/oferta/crear.tsx
  frontend/app/oferta/editar/[ofertaid].tsx
  frontend/app/suscripcion/index.tsx
  frontend/contexts/SubscriptionContext.tsx
  frontend/security/EmpresaRoute.js
Labels: Review effort 3/5

#166 Reseñas en frontend
  frontend/app/_screens/MiPerfilCamionero.tsx
  frontend/app/_screens/MiPerfilEmpresa.tsx
  frontend/app/_screens/PublicCamionero.tsx
  frontend/app/_screens/PublicEmpresa.tsx
Labels: Review effort 3/5

#163 Añadir seccion mis ofertas + fix back button empresa
  frontend/app/(public)/camionero/[camioneroid].tsx
  frontend/app/(public)/empresas.tsx
  frontend/app/(public)/index.tsx
  frontend/app/_components/CamyoNavBar.jsx
  frontend/app/_components/ListadoOfertas.tsx
  frontend/app/_components/routes.ts
  frontend/app/_layout.tsx
  frontend/app/_screens/MiPerfilCamionero.tsx
  frontend/app/_screens/MiPerfilEmpresa.tsx
  frontend/app/_screens/MisOfertasCamionero.tsx
  frontend/app/_screens/MisOfertasEmpresa.tsx
  frontend/app/_screens/PublicCamionero.tsx
  frontend/app/_screens/PublicEmpresa.tsx
  frontend/app/misofertas/index.tsx
  frontend/app/oferta/[ofertaid].tsx
  frontend/contexts/AuthContext.tsx
  frontend/utils/apiUtils.js
  frontend/utils/unifyData.js
Labels: Review effort 3/5

#168 Added promoted attribute in Offer and updated sponsorship se…
  backend/src/main/java/com/camyo/backend/oferta/Oferta.java
  backend/src/main/java/com/camyo/backend/oferta/OfertaPatrocinadaRepository.java
  backend/src/main/java/com/camyo/backend/oferta/OfertaPatrocinadaService.java
Labels: Review effort 2/5

#169 Adds OfferType field to company and trucker endpoints
  backend/src/main/java/com/camyo/backend/oferta/OfertaController.java
  backend/src/main/java/com/camyo/backend/oferta/OfertaService.java
Labels: Review effort 2/5

#167 Cambio del Navbar y de la página principal
  frontend/app/(public)/index.tsx
  frontend/app/_components/CamyoNavBar.jsx
  frontend/app/_components/OptionsDropdown.js
  frontend/app/_components/ProfileDropdown.js
  frontend/app/buscar-ofertas/index.tsx
  frontend/assets/images/camion.png
  frontend/assets/images/camyo.png
  frontend/assets/images/camyoV1.png
  frontend/assets/images/camyoV2.png
  frontend/package-lock.json
  frontend/package.json
Labels: Review effort 3/5

#172 Añadir casilla aceptar terminos y condiciones en registro de usuario
  frontend/app/(public)/registro/camionero.tsx
  frontend/app/(public)/registro/empresa.tsx
  frontend/assets/gdpr.ts
Labels: Review effort 2/5, frontend

#165 Reseña solo si existe oferta común
  backend/src/main/java/com/camyo/backend/configuration/DataInitializer.java
  backend/src/main/java/com/camyo/backend/resena/ResenaController.java
  backend/src/main/java/com/camyo/backend/usuario/UsuarioRepository.java
  backend/src/main/java/com/camyo/backend/usuario/UsuarioService.java
Labels: Review effort 3/5

#175 Corrected promoted field that appeared as null in DTO
  backend/src/main/java/com/camyo/backend/oferta/OfertaCompletaDTO.java
  backend/src/main/java/com/camyo/backend/oferta/OfertaController.java
Labels: Review effort 1/5

#159 Rediseñar estilos y funcionalidades del chat
  frontend/app/(public)/empresas.tsx
  frontend/app/_components/CamyoNavBar.jsx
  frontend/app/_components/routes.ts
  frontend/app/_screens/PublicCamionero.tsx
  frontend/app/chat/chat.tsx
  frontend/app/chat/index.tsx
  frontend/app/chat/list.tsx
  frontend/package-lock.json
Labels: feat, Review effort 3/5, frontend

#177 Añadir botón de Explorar Ofertas en el menú desplegable
  frontend/app/_components/CamyoNavBar.jsx
  frontend/app/_components/OptionsDropdown.js
Labels: Review effort 2/5

#176 DatePicker como componente para los formularios
  frontend/app/_components/BooleanSelector.tsx
  frontend/app/_components/DatePicker.tsx
  frontend/app/_components/Selector.tsx
  frontend/app/oferta/crear.tsx
  frontend/package-lock.json
  frontend/package.json
Labels: Review effort 2/5

#181 Tests de CamioneroController y CamioneroService
  backend/src/main/java/com/camyo/backend/camionero/Camionero.java
  backend/src/main/java/com/camyo/backend/camionero/CamioneroController.java
  backend/src/main/java/com/camyo/backend/configuration/DataInitializer.java
  backend/src/main/java/com/camyo/backend/oferta/OfertaPatrocinadaService.java
  backend/src/test/java/com/camyo/backend/Camionero/CamioneroControllerTests.java
  backend/src/test/java/com/camyo/backend/Camionero/CamioneroServiceTests.java
  backend/src/test/resources/application-test.properties.example
Labels: Review effort 2/5

#183 Pilot Test User Database and some fixes
  backend/src/main/java/com/camyo/backend/configuration/DataInitializer.java
  backend/src/main/java/com/camyo/backend/oferta/OfertaConTodaInformacionDTO.java
  backend/src/main/java/com/camyo/backend/oferta/OfertaController.java
  backend/src/main/java/com/camyo/backend/oferta/OfertaPatrocinadaService.java
  backend/src/main/java/com/camyo/backend/oferta/OfertaRepository.java
  backend/src/main/java/com/camyo/backend/suscripcion/Suscripcion.java
  backend/src/main/java/com/camyo/backend/suscripcion/SuscripcionController.java
  backend/src/main/java/com/camyo/backend/suscripcion/SuscripcionRepository.java
  backend/src/main/java/com/camyo/backend/suscripcion/SuscripcionService.java
  backend/src/test/java/com/camyo/backend/Camionero/CamioneroControllerTests.java
  frontend/app/oferta/crear.tsx
  frontend/app/suscripcion/index.tsx
  frontend/contexts/SubscriptionContext.tsx
  frontend/utils/subscriptionRules.ts
Labels: Review effort 2/5

#186 Patrocinar Ofertas
  frontend/app/_screens/MiPerfilCamionero.tsx
  frontend/app/_screens/MiPerfilEmpresa.tsx
Labels: Review effort 3/5, frontend

#187 Patrocinado to Buscar Ofertas and Home Page
  backend/src/main/java/com/camyo/backend/oferta/OfertaController.java
  backend/src/main/java/com/camyo/backend/oferta/OfertaRepository.java
  frontend/app/(public)/index.tsx
  frontend/app/buscar-ofertas/index.tsx
Labels: Review effort 2/5, frontend

#188 Cambios visuales TOCHOS.
  frontend/app/(public)/index.tsx
  frontend/app/_components/Testimonios.tsx
  frontend/app/suscripcion/index.tsx
  frontend/assets/images/lonely-road.jpg
  frontend/package-lock.json
  frontend/package.json
  frontend/security/AdminRoute.js
  frontend/utils/subscriptionRules.ts
Labels: Review effort 3/5

#189 Cambios estéticos! (menores)
  frontend/app/(public)/empresas.tsx
  frontend/app/(public)/index.tsx
  frontend/app/_components/SuccessModal.tsx
  frontend/app/_components/WebFooter.tsx
  frontend/app/_layout.tsx
  frontend/app/buscar-ofertas/index.tsx
Labels: Review effort 2/5

#197 Rediseño pasarela de pago, arreglo de parámetros de suscripciones y pantallas de términos y privacidad.
  frontend/app/(protected)/pago/checkout.tsx
  frontend/app/(protected)/suscripcion/index.tsx
  frontend/app/(public)/privacidad.tsx
  frontend/app/(public)/registro/camionero.tsx
  frontend/app/(public)/registro/empresa.tsx
  frontend/app/(public)/terminos.tsx
  frontend/app/_components/_layout/WebFooter.tsx
  frontend/app/_layout.tsx
  frontend/assets/gdpr.ts
  frontend/assets/legalData.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/utils/productDetails.ts
  frontend/utils/subscriptionRules.ts
Labels: Review effort 3/5, frontend

#199 Mejora de filtros y UI.
  backend/src/main/java/com/camyo/backend/camionero/Licencia.java
  frontend/app/(public)/explorar.tsx
Labels: Review effort 3/5, frontend
