Repository Camyo-ISPP/CamyoApp, pull requests merged in 2025-04, with the labels that each got.

#202 Implementar mapas en ofertas de carga
  frontend/app/_components/CityPicker.tsx
  frontend/app/_components/Maps.tsx
  frontend/app/oferta/[ofertaid].tsx
  frontend/app/oferta/crear.tsx
  frontend/package-lock.json
Labels: feat, Review effort 3/5, frontend

#211 Subscription Logic in Routes
  frontend/app/(public)/index.tsx
  frontend/app/oferta/crear.tsx
Labels: Review effort 3/5

#206 Añadir CV de camionero
  backend/src/main/java/com/camyo/backend/auth/AuthService.java
  backend/src/main/java/com/camyo/backend/auth/payload/request/EditRequestCamionero.java
  backend/src/main/java/com/camyo/backend/auth/payload/request/EditRequestEmpresa.java
  backend/src/main/java/com/camyo/backend/auth/payload/request/SignupRequestCamionero.java
  backend/src/main/java/com/camyo/backend/camionero/Camionero.java
  frontend/app/(public)/registro/camionero.tsx
  frontend/app/_screens/EditarPerfilCamionero.tsx
  frontend/app/_screens/EditarPerfilEmpresa.tsx
  frontend/app/_screens/MiPerfilCamionero.tsx
  frontend/app/_screens/PublicCamionero.tsx
  frontend/package.json
  frontend/utils/unifyData.js
Labels: Review effort 2/5

#219 Añadir más tests unitarios y de integración para las funciones de oferta
  backend/src/test/java/com/camyo/backend/Oferta/CargaServiceTest.java
  backend/src/test/java/com/camyo/backend/Oferta/OfertaControllerTests.java
  backend/src/test/java/com/camyo/backend/Oferta/OfertaServiceTests.java
  backend/src/test/java/com/camyo/backend/Oferta/TrabajoServiceTests.java
Labels: Review effort 2/5

#218 Añadir pago al patrocinio de ofertas
  backend/src/main/java/com/camyo/backend/pago/PagoController.java
  backend/src/main/java/com/camyo/backend/pago/RequestDTO.java
  frontend/app/(protected)/pago/checkout.tsx
  frontend/app/_components/ListadoOfertasEmpresa.tsx
  frontend/app/_screens/MiPerfilEmpresa.tsx
  frontend/contexts/PaymentContext.tsx
Labels: Review effort 3/5

#223 Mejorar Estilo Chat
  frontend/app/(protected)/chat/chat.tsx
  frontend/app/(protected)/chat/index.tsx
  frontend/app/(public)/explorar.tsx
  frontend/app/(public)/index.tsx
  frontend/app/_screens/MiPerfilCamionero.tsx
Labels: Review effort 3/5

#232 Arreglar márgenes de terminos y condiciones
  frontend/app/(public)/privacidad.tsx
  frontend/app/(public)/terminos.tsx
Labels: Review effort 1/5

#233 testing de oferta
  backend/src/test/java/com/camyo/backend/Oferta/OfertaControllerTests.java
  backend/src/test/java/com/camyo/backend/Oferta/OfertaServiceTests.java
Labels: Review effort 3/5

#234 Implementar panel admin
  backend/src/main/java/com/camyo/backend/camion/Camion.java
  backend/src/main/java/com/camyo/backend/camion/CamionRepository.java
  backend/src/main/java/com/camyo/backend/camion/CamionService.java
  backend/src/main/java/com/camyo/backend/camionero/Camionero.java
  backend/src/main/java/com/camyo/backend/camionero/CamioneroController.java
  backend/src/main/java/com/camyo/backend/camionero/CamioneroService.java
  backend/src/main/java/com/camyo/backend/configuration/DataInitializer.java
  backend/src/main/java/com/camyo/backend/configuration/SecurityConfiguration.java
  backend/src/main/java/com/camyo/backend/empresa/EmpresaController.java
  backend/src/main/java/com/camyo/backend/empresa/EmpresaService.java
  backend/src/main/java/com/camyo/backend/resena/Resena.java
  backend/src/main/java/com/camyo/backend/suscripcion/Suscripcion.java
  backend/src/main/java/com/camyo/backend/usuario/UsuarioController.java
  backend/src/main/java/com/camyo/backend/usuario/UsuarioService.java
  frontend/app/(admin)/admin.tsx
  frontend/app/(admin)/workinprogress.tsx
  frontend/app/(public)/empresas.tsx
  frontend/app/(public)/explorar.tsx
  frontend/app/(public)/index.tsx
  frontend/app/(public)/login.tsx
  frontend/app/_components/ConfirmDeleteModal.tsx
  frontend/app/_components/ListadoOfertasPublico.tsx
  frontend/app/_components/_layout/CamyoNavBar.jsx
  frontend/app/_components/_layout/OptionsDropdown.js
  frontend/app/_layout.tsx
  frontend/app/_screens/AdminPanel.tsx
  frontend/app/_screens/MisOfertasCamionero.tsx
  frontend/app/_screens/MisOfertasEmpresa.tsx
  frontend/security/ProtectedRoute.js
Labels: Review effort 3/5

#239 Comprobar validaciones
  frontend/app/(public)/registro/camionero.tsx
  frontend/app/(public)/registro/empresa.tsx
  frontend/app/_screens/EditarPerfilCamionero.tsx
  frontend/app/_screens/EditarPerfilEmpresa.tsx
  frontend/app/oferta/crear.tsx
Labels: Review effort 3/5, frontend

#241 Añadir opción para eliminar cuenta
  backend/src/main/java/com/camyo/backend/configuration/SecurityConfiguration.java
  backend/src/main/java/com/camyo/backend/suscripcion/Suscripcion.java
  backend/src/main/java/com/camyo/backend/usuario/UsuarioController.java
  frontend/app/_components/ErrorModal.tsx
  frontend/app/_screens/MiPerfilCamionero.tsx
  frontend/app/_screens/MiPerfilEmpresa.tsx
Labels: Review effort 3/5

#216 test: add testing for reseña,suscripcion and usuario
  backend/src/test/java/com/camyo/backend/BackendApplicationTests.java
  backend/src/test/java/com/camyo/backend/resena/ResenaControllerTests.java
  backend/src/test/java/com/camyo/backend/resena/ResenaServiceTests.java
  backend/src/test/java/com/camyo/backend/suscripcion/SuscripcionControllerTests.java
  backend/src/test/java/com/camyo/backend/suscripcion/SuscripcionServiceTests.java
  backend/src/test/java/com/camyo/backend/usuario/UsuarioControllerTests.java
  backend/src/test/java/com/camyo/backend/usuario/UsuarioServiceTests.java
Labels: Review effort 2/5

#242 Encripcion DNI y arreglo de tests
  backend/.env.example
  backend/src/main/java/com/camyo/backend/BackendApplication.java
  backend/src/main/java/com/camyo/backend/camionero/Camionero.java
  backend/src/main/java/com/camyo/backend/camionero/CamioneroService.java
  backend/src/main/java/com/camyo/backend/configuration/DataInitializer.java
  backend/src/main/java/com/camyo/backend/util/EncryptionService.java
  backend/src/test/java/com/camyo/backend/Camionero/CamioneroControllerTests.java
  backend/src/test/java/com/camyo/backend/Camionero/CamioneroServiceTests.java
  backend/src/test/java/com/camyo/backend/Empresa/EmpresaControllerTests.java
  backend/src/test/java/com/camyo/backend/Empresa/EmpresaServiceTests.java
  backend/src/test/resources/application-test.properties.example
Labels: Review effort 3/5

#243 Add more test cases to increase coverage of OfertaController and…
  backend/src/main/java/com/camyo/backend/oferta/PatrocinioStatus.java
  backend/src/test/java/com/camyo/backend/Oferta/OfertaControllerTests.java
  backend/src/test/java/com/camyo/backend/Oferta/OfertaServiceTests.java
Labels: Review effort 2/5

#245 Add more testing to have more coverage
  backend/src/test/java/com/camyo/backend/Resena/ResenaControllerTests.java
  backend/src/test/java/com/camyo/backend/Resena/ResenaServiceTests.java
  backend/src/test/java/com/camyo/backend/Suscripcion/SuscripcionControllerTests.java
  backend/src/test/java/com/camyo/backend/Suscripcion/SuscripcionServiceTests.java
  backend/src/test/java/com/camyo/backend/Usuario/AuthoritiesServiceTests.java
  backend/src/test/java/com/camyo/backend/Usuario/UsuarioControllerTests.java
  backend/src/test/java/com/camyo/backend/Usuario/UsuarioEntityTests.java
  backend/src/test/java/com/camyo/backend/Usuario/UsuarioServiceTests.java
  backend/src/test/java/com/camyo/backend/resena/ResenaControllerTests.java
  backend/src/test/java/com/camyo/backend/resena/ResenaServiceTests.java
  backend/src/test/java/com/camyo/backend/suscripcion/SuscripcionControllerTests.java
  backend/src/test/java/com/camyo/backend/suscripcion/SuscripcionServiceTests.java
  backend/src/test/java/com/camyo/backend/usuario/UsuarioControllerTests.java
  backend/src/test/java/com/camyo/backend/usuario/UsuarioServiceTests.java
Labels: Review effort 2/5

#244 Fixes + UI/UX improvements
  backend/src/main/java/com/camyo/backend/auth/AuthController.java
  backend/src/main/java/com/camyo/backend/auth/AuthService.java
  backend/src/main/java/com/camyo/backend/auth/payload/request/EditRequestCamionero.java
  backend/src/main/java/com/camyo/backend/configuration/DataInitializer.java
  backend/src/main/java/com/camyo/backend/oferta/OfertaConTodaInformacionDTO.java
  backend/src/main/java/com/camyo/backend/oferta/OfertaController.java
  frontend/app/(public)/index.tsx
  frontend/app/(public)/login.tsx
  frontend/app/_components/ListadoOfertasPublico.tsx
  frontend/app/_screens/EditarPerfilCamionero.tsx
  frontend/app/_screens/MiPerfilEmpresa.tsx
  frontend/app/_screens/MisOfertasCamionero.tsx
  frontend/app/_screens/PublicEmpresa.tsx
  frontend/app/oferta/[ofertaid].tsx
  frontend/hoc/withNavigationGuard.tsx
Labels: Review effort 3/5

#247 Validaciones de backend
  backend/src/main/java/com/camyo/backend/auth/AuthController.java
  backend/src/main/java/com/camyo/backend/auth/AuthService.java
  backend/src/main/java/com/camyo/backend/auth/payload/request/EditRequestCamionero.java
  backend/src/main/java/com/camyo/backend/auth/payload/request/EditRequestEmpresa.java
  backend/src/main/java/com/camyo/backend/auth/payload/request/SignupRequestCamionero.java
  backend/src/main/java/com/camyo/backend/auth/payload/request/SignupRequestEmpresa.java
  backend/src/main/java/com/camyo/backend/camionero/Camionero.java
  backend/src/main/java/com/camyo/backend/camionero/CamioneroService.java
  backend/src/main/java/com/camyo/backend/empresa/EmpresaService.java
  backend/src/main/java/com/camyo/backend/exceptions/InvalidNifException.java
  backend/src/main/java/com/camyo/backend/exceptions/InvalidPhoneNumberException.java
  backend/src/main/java/com/camyo/backend/usuario/Usuario.java
  backend/src/main/java/com/camyo/backend/usuario/UsuarioService.java
  backend/src/main/java/com/camyo/backend/util/Validators.java
  backend/src/test/java/com/camyo/backend/Camionero/CamioneroServiceTests.java
  backend/src/test/java/com/camyo/backend/Empresa/EmpresaServiceTests.java
  backend/src/test/java/com/camyo/backend/Usuario/UsuarioServiceTests.java
Labels: Review effort 3/5

#236 Tarea de borradores
  backend/src/main/java/com/camyo/backend/oferta/OfertaController.java
  frontend/app/_components/CityPicker.tsx
  frontend/app/_components/ConfirmDeleteDraft.tsx
  frontend/app/_components/DraftModal.tsx
  frontend/app/_components/ListadoOfertasBorrador.tsx
  frontend/app/_layout.tsx
  frontend/app/_screens/MiPerfilEmpresa.tsx
  frontend/app/_screens/MisOfertasEmpresa.tsx
  frontend/app/oferta/[ofertaid]/editar.tsx
  frontend/app/oferta/crear.tsx
Labels: feat, fix, Review effort 4/5, frontend

#230 Arreglar lógica reseñas
  backend/src/main/java/com/camyo/backend/resena/Resena.java
  frontend/app/(protected)/pago/checkout.tsx
  frontend/app/(public)/explorar.tsx
  frontend/app/_components/ListadoOfertasPublico.tsx
  frontend/app/_components/ResenaModal.tsx
  frontend/app/_screens/MiPerfilCamionero.tsx
  frontend/app/_screens/MiPerfilEmpresa.tsx
  frontend/app/_screens/MisOfertasEmpresa.tsx
  frontend/app/_screens/PublicCamionero.tsx
  frontend/app/_screens/PublicEmpresa.tsx
  frontend/app/oferta/crear.tsx
Labels: Review effort 4/5, frontend

#252 Add more unit tests to increase coverage for Oferta
  backend/src/test/java/com/camyo/backend/Oferta/OfertaControllerTests.java
  backend/src/test/java/com/camyo/backend/Oferta/OfertaServiceTests.java
Labels: Review effort 2/5

#250 Implementar anuncios manuales
  backend/src/main/java/com/camyo/backend/configuration/DataInitializer.java
  backend/src/main/java/com/camyo/backend/configuration/SecurityConfiguration.java
  backend/src/main/java/com/camyo/backend/pago/PagoController.java
  backend/src/main/java/com/camyo/backend/usuario/Usuario.java
  backend/src/main/java/com/camyo/backend/usuario/UsuarioService.java
  frontend/app.config.js
  frontend/app/(protected)/pago/checkout.tsx
  frontend/app/(public)/empresas.tsx
  frontend/app/(public)/explorar.tsx
  frontend/app/(public)/index.tsx
  frontend/app/_components/AdSense.tsx
  frontend/app/_components/PopUpAd.tsx
  frontend/app/_layout.tsx
  frontend/app/_screens/EditarPerfilCamionero.tsx
  frontend/app/_screens/EditarPerfilEmpresa.tsx
  frontend/app/_screens/MiPerfilCamionero.tsx
  frontend/app/_screens/MiPerfilEmpresa.tsx
  frontend/app/miperfil/index.tsx
  frontend/assets/images/truck_mockup_ad.jpg
  frontend/google14474bfd311675a6.html
  frontend/index.html
  frontend/utils/productDetails.ts
  frontend/utils/unifyData.js
  package-lock.json
  package.json
Labels: Review effort 3/5

#259 Mejoras a suscripciones y patrocinios.
  frontend/app/(protected)/pago/checkout.tsx
  frontend/app/(protected)/suscripcion/index.tsx
  frontend/app/_components/ListadoOfertasEmpresa.tsx
  frontend/app/_components/SubscriptionModal.tsx
Labels: Review effort 2/5

#261 Arreglos de Mi Perfil (mejorar plan button + eliminar cuenta button)
  frontend/app/_screens/MiPerfilCamionero.tsx
  frontend/app/_screens/MiPerfilEmpresa.tsx
Labels: Review effort 2/5

#260 Mejoras Listado de Ofertas
  backend/src/main/java/com/camyo/backend/oferta/OfertaConTodaInformacionPlanarDTO.java
  backend/src/main/java/com/camyo/backend/oferta/OfertaController.java
  backend/src/main/java/com/camyo/backend/oferta/OfertaRepository.java
  backend/src/main/java/com/camyo/backend/oferta/OfertaService.java
  frontend/app/(public)/explorar.tsx
Labels: Review effort 3/5

#263 Configuración UI.
  backend/pom.xml
  backend/src/test/java/com/camyo/backend/UI/EjemploUITest.java
Labels: Review effort 2/5

#262 Mejoras al chat
  frontend/app/(protected)/chat/chat.tsx
  frontend/app/(protected)/chat/index.tsx
  frontend/app/_screens/PublicEmpresa.tsx
  package-lock.json
Labels: feat, Review effort 2/5, frontend

#270 Modify nifs and phone numbers
  backend/src/main/java/com/camyo/backend/configuration/DataInitializer.java
Labels: Review effort 2/5

#268 Fix dropdown behaviour and improved them
  frontend/app/_components/_layout/CamyoNavBar.jsx
  frontend/app/_components/_layout/OptionsDropdown.js
  frontend/app/_components/_layout/ProfileDropdown.js
  frontend/tsconfig.json
Labels: Review effort 2/5, frontend

#285 Carlos 2 Frontend Fixes
  backend/src/main/java/com/camyo/backend/auth/AuthService.java
  backend/src/main/java/com/camyo/backend/auth/payload/request/EditRequestCamionero.java
  backend/src/main/java/com/camyo/backend/auth/payload/request/EditRequestEmpresa.java
  backend/src/main/java/com/camyo/backend/camionero/CamioneroService.java
  frontend/app/(protected)/suscripcion/index.tsx
  frontend/app/(public)/empresas.tsx
  frontend/app/(public)/explorar.tsx
  frontend/app/(public)/registro/camionero.tsx
  frontend/app/(public)/registro/empresa.tsx
  frontend/app/_components/CityPicker.tsx
  frontend/app/_components/DatePicker.tsx
  frontend/app/_components/ListadoOfertasBorrador.tsx
  frontend/app/_components/ListadoOfertasEmpresa.tsx
  frontend/app/_components/ListadoOfertasPublico.tsx
  frontend/app/_components/ListadoOfertasPublicoSmall.tsx
  frontend/app/_screens/EditarPerfilCamionero.tsx
  frontend/app/_screens/EditarPerfilEmpresa.tsx
  frontend/app/_screens/MiPerfilCamionero.tsx
  frontend/app/_screens/MiPerfilEmpresa.tsx
  frontend/app/_screens/PublicCamionero.tsx
  frontend/app/_screens/PublicEmpresa.tsx
  frontend/app/oferta/[ofertaid].tsx
  frontend/app/oferta/[ofertaid]/editar.tsx
  frontend/app/oferta/crear.tsx
Labels: Review effort 3/5
